# **Parte 1 — Preparação do ambiente**

Execute no Google Colab:

import pandas as pd

Carregue o dataset:

df = pd.read_csv('/content/qualidade_ar_brasil.csv')

In [ ]:
import pandas as pd
df = pd.read_csv('/content/qualidade_ar_brasil.csv')
df.head(100)

,data,cidade,estado,pm25,pm10,no2,o3,temperatura,umidade,indice_qualidade_ar,nivel_alerta
0,2025-01-01,Brasília,DF,33.7,60.9,44.6,31.8,25.5,57.8,61.7,Moderado
1,2025-01-01,Curitiba,PR,25.7,22.1,29.4,40.0,17.1,77.4,43.4,Moderado
2,2025-01-01,Salvador,BA,18.8,27.6,29.2,60.2,29.3,78.0,47.5,Moderado
3,2025-01-02,Curitiba,PR,12.4,41.1,20.0,32.6,20.3,85.7,35.8,Bom
4,2025-01-03,Belo Horizonte,MG,32.0,57.3,36.4,23.5,26.3,74.6,54.1,Moderado
...,...,...,...,...,...,...,...,...,...,...,...
95,2025-02-14,Rio de Janeiro,RJ,21.1,46.9,14.2,42.0,27.9,69.9,42.9,Moderado
96,2025-02-16,Belo Horizonte,MG,22.0,47.9,33.3,12.8,27.5,61.7,41.6,Moderado
97,2025-02-16,Fortaleza,CE,20.2,43.9,29.1,44.1,31.4,73.0,47.8,Moderado
98,2025-02-16,Porto Alegre,RS,19.0,49.2,28.9,31.2,23.2,71.7,44.5,Moderado
99,2025-02-17,Brasília,DF,23.5,63.0,31.9,39.5,27.2,54.3,54.5,Moderado

# **Parte 2 — Inspeção inicial do dataset**

**Execute os comandos:**

df.shape
df.head()
df.info()
df.describe()
df.isnull().sum()

**Perguntas**

1. Quantas medições existem no dataset?

    **R: 11**

2. Quantas cidades estão presentes na base?

    **R: **

3. Quais colunas representam poluentes atmosféricos?

    **R: pm25, pm10, no2, o3**

4. Existem valores ausentes no dataset?

    **R: Não**

In [ ]:
#df.shape
#df.head()
#df.info()
#df.describe()
#df.isnull().sum()

data                   0
cidade                 0
estado                 0
pm25                   0
pm10                   0
no2                    0
o3                     0
temperatura            0
umidade                0
indice_qualidade_ar    0
nivel_alerta           0
dtype: int64

# **Parte 3 — Análise por cidade**

**Liste as cidades presentes no dataset:**

df['cidade'].unique()

**Calcule a média de poluição por cidade:**

df.groupby('cidade')[['pm25','pm10','no2','o3']].mean()

**Perguntas**
1. Qual cidade apresenta maior média de PM2.5?

    **R: São Paulo**

2. Qual cidade apresenta maior média de NO2?

    **R: São Paulo**

3. Existe alguma cidade com níveis consistentemente mais altos de poluentes?

In [ ]:
cidades = df['cidade'].unique()
print('Cidades:', cidades)
#df.groupby('cidade')[['pm25']].mean().sort_values(by='pm25', ascending=False)
#df.groupby('cidade')[['no2']].mean().sort_values(by='no2', ascending=False)

Cidades: ['Brasília' 'Curitiba' 'Salvador' 'Belo Horizonte' 'Recife' 'Fortaleza'
 'Rio de Janeiro' 'Porto Alegre' 'Manaus' 'São Paulo']

# **Parte 4 — Análise do índice de qualidade do ar**

**Calcule a média do índice de qualidade do ar por cidade:**

df.groupby('cidade')['indice_qualidade_ar'].mean().sort_values
(ascending=False)

**Perguntas**

1. Qual cidade apresenta pior qualidade média do ar?

    **R: São Paulo**

2. Qual cidade apresenta melhor qualidade do ar?

    **R: Salvador**

In [ ]:
indice_qualidade = df.groupby('cidade')['indice_qualidade_ar'].mean().sort_values (ascending=False)
print(indice_qualidade)

cidade
São Paulo         59.345312
Brasília          54.955172
Rio de Janeiro    50.639759
Belo Horizonte    48.344156
Porto Alegre      46.898592
Manaus            45.092771
Fortaleza         44.646250
Curitiba          44.359140
Recife            43.198824
Salvador          42.342857
Name: indice_qualidade_ar, dtype: float64

# **Parte 5 — Filtragem por nível de alerta**

Filtre apenas registros classificados como Ruim ou Muito Ruim.

df_alerta = df[df['nivel_alerta'].isin(['Ruim','Muito Ruim'])]

df_alerta.head()

**Perguntas**

1. Quantos registros possuem alerta crítico?

    **R: 20**

2. Em quais cidades eles ocorrem com maior frequência?
    **R: São Paulo e Rio de Janeiro**

In [ ]:
df_alerta = df[df['nivel_alerta'].isin(['Ruim','Muito Ruim'])]

df_alerta.head(20)

,data,cidade,estado,pm25,pm10,no2,o3,temperatura,umidade,indice_qualidade_ar,nivel_alerta
235,2025-04-20,São Paulo,SP,33.7,73.7,57.2,34.3,25.9,61.1,70.8,Ruim
319,2025-06-01,Rio de Janeiro,RJ,45.1,70.1,37.4,48.0,28.1,78.9,72.7,Ruim
320,2025-06-02,Manaus,AM,53.6,79.5,25.2,36.2,31.7,74.9,71.6,Ruim
347,2025-06-17,Brasília,DF,52.7,79.1,35.4,31.9,28.6,51.0,73.5,Ruim
358,2025-06-20,Belo Horizonte,MG,44.5,78.9,41.8,46.1,27.0,64.8,75.9,Ruim
379,2025-07-03,São Paulo,SP,51.7,78.9,48.3,26.8,21.6,68.0,76.1,Ruim
402,2025-07-12,São Paulo,SP,43.1,64.6,35.4,50.1,23.4,74.6,70.0,Ruim
408,2025-07-15,São Paulo,SP,38.3,72.1,35.3,53.2,23.9,66.8,70.5,Ruim
410,2025-07-15,São Paulo,SP,42.4,87.6,44.6,40.2,21.2,74.7,76.5,Ruim
411,2025-07-15,São Paulo,SP,35.8,91.6,41.6,36.7,22.4,79.9,71.8,Ruim
431,2025-07-27,São Paulo,SP,60.1,50.0,56.4,54.8,25.2,76.3,84.3,Ruim
488,2025-08-19,São Paulo,SP,55.2,78.8,55.0,45.3,20.3,80.3,86.3,Ruim
498,2025-08-22,Rio de Janeiro,RJ,44.5,58.9,41.7,45.8,26.1,81.9,70.2,Ruim
548,2025-09-17,Brasília,DF,54.3,69.2,37.4,36.0,23.8,62.5,73.6,Ruim

# **Parte 6 — Ranking dos dias mais críticos**

**Descubra os dias com pior qualidade do ar:**

df.sort_values('indice_qualidade_ar', ascending=False).head(10)

**Perguntas**

1. Qual foi o pior dia registrado?

    **R: 19/08/2025**

2. Em qual cidade ocorreu?

    **R: São Paulo**

3. Quais poluentes estavam mais altos nesse dia?

    **R: PM10 e PM25**

In [ ]:
df.sort_values('indice_qualidade_ar', ascending=False).head(10)

,data,cidade,estado,pm25,pm10,no2,o3,temperatura,umidade,indice_qualidade_ar,nivel_alerta
488,2025-08-19,São Paulo,SP,55.2,78.8,55.0,45.3,20.3,80.3,86.3,Ruim
431,2025-07-27,São Paulo,SP,60.1,50.0,56.4,54.8,25.2,76.3,84.3,Ruim
410,2025-07-15,São Paulo,SP,42.4,87.6,44.6,40.2,21.2,74.7,76.5,Ruim
379,2025-07-03,São Paulo,SP,51.7,78.9,48.3,26.8,21.6,68.0,76.1,Ruim
358,2025-06-20,Belo Horizonte,MG,44.5,78.9,41.8,46.1,27.0,64.8,75.9,Ruim
548,2025-09-17,Brasília,DF,54.3,69.2,37.4,36.0,23.8,62.5,73.6,Ruim
347,2025-06-17,Brasília,DF,52.7,79.1,35.4,31.9,28.6,51.0,73.5,Ruim
319,2025-06-01,Rio de Janeiro,RJ,45.1,70.1,37.4,48.0,28.1,78.9,72.7,Ruim
411,2025-07-15,São Paulo,SP,35.8,91.6,41.6,36.7,22.4,79.9,71.8,Ruim
320,2025-06-02,Manaus,AM,53.6,79.5,25.2,36.2,31.7,74.9,71.6,Ruim

# **Parte 7 — Análise temporal**

**Converta a coluna de data:**

df['data'] = pd.to_datetime(df['data'])

**Crie a coluna de mês:**

df['mes'] = df['data'].dt.month

**Agora calcule a média do índice por mês:**

df.groupby('mes')['indice_qualidade_ar'].mean()

**Perguntas**

1. Em quais meses a qualidade do ar tende a ser pior?

    **R: Nos meses 6 e 7**

2. Existe algum padrão sazonal?

    **R: Cresce até o pico no meio do ano, depois decresce.**

In [ ]:
df['data'] = pd.to_datetime(df['data'])
df['mes'] = df['data'].dt.month
df.groupby('mes')['indice_qualidade_ar'].mean()

mes
1     44.852308
2     42.985714
3     46.675949
4     47.559259
5     47.107813
6     52.881034
7     51.293443
8     49.640000
9     49.923333
10    47.865385
11    46.861429
12    45.829333
Name: indice_qualidade_ar, dtype: float64

# **Parte 8 — Correlação entre variáveis**

**Verifique se há relação entre temperatura e poluição.**

df[['temperatura','pm25','pm10','no2','o3']].corr()

**Perguntas**

1. Existe correlação entre temperatura e poluição?

    **R: O NO2 apresenta a maior correlação negativa com a temperatura (-0,169), enquanto o O3 apresenta uma correlação positiva (0,161), mas ambas são fracas.**

2. Quais poluentes parecem mais relacionados entre si?

    **R: os poluentes que mais apresentam relação entre si são PM2.5 e PM10, com correlação de aproximadamente 0,25.**

In [ ]:
df[['temperatura','pm25','pm10','no2','o3']].corr()

             temperatura      pm25      pm10       no2        o3
temperatura     1.000000 -0.114987 -0.112821 -0.168689  0.160547
pm25           -0.114987  1.000000  0.253494  0.124651  0.022676
pm10           -0.112821  0.253494  1.000000  0.151211 -0.002501
no2            -0.168689  0.124651  0.151211  1.000000  0.048104
o3              0.160547  0.022676 -0.002501  0.048104  1.000000

# **Desafio Final — Relatório para o Ministério**
**Elabore um pequeno relatório respondendo:**
1. Qual cidade apresenta pior qualidade média do ar?

    **R: São Paulo**

2. Quais poluentes são mais críticos?

    **R: PM10 e O3**

3. Existem meses mais problemáticos?

    **R: Junho e Julho**

4. Quais cidades deveriam receber maior atenção das autoridades ambientais?

    **R: São Paulo, Brasília e Rio de Janeiro**

In [ ]:
#1
#media_cidades = df.groupby('cidade')[['pm25', 'pm10', 'no2', 'o3']].mean()

#media_cidades['media_poluição'] = media_cidades.mean(axis=1)

#media_cidades.sort_values('media_poluição', ascending=False)

#2
#media_poluentes = df[['pm25', 'pm10', 'no2', 'o3']].mean()

#media_poluentes.sort_values(ascending=False)

#3
#media_meses = df.groupby('mes')[['pm25', 'pm10', 'no2', 'o3']].mean()

#media_meses['media_poluição'] = media_meses.mean(axis=1)

#media_meses.sort_values('media_poluição', ascending=False)

#4
media_cidades.sort_values('media_poluição', ascending=False).head(3)

                     pm25       pm10        no2         o3  media_poluição
cidade
São Paulo       33.653125  56.256250  39.314062  34.878125       41.025391
Brasília        31.351724  59.428736  29.926437  33.167816       38.468678
Rio de Janeiro  27.825301  43.106024  30.925301  38.836145       35.173193